In [355]:
import pandas as pd
import numpy as np

In [356]:
# carrega o arquivo xlsx em um dataframe do pandas
dataset = pd.read_excel('dataset.xlsx')
dataset

,Patient ID,Patient age quantile,SARS-Cov-2 exam result,"Patient addmited to regular ward (1=yes, 0=no)","Patient addmited to semi-intensive unit (1=yes, 0=no)","Patient addmited to intensive care unit (1=yes, 0=no)",Hematocrit,Hemoglobin,Platelets,Mean platelet volume,...,Hb saturation (arterial blood gases),pCO2 (arterial blood gas analysis),Base excess (arterial blood gas analysis),pH (arterial blood gas analysis),Total CO2 (arterial blood gas analysis),HCO3 (arterial blood gas analysis),pO2 (arterial blood gas analysis),Arteiral Fio2,Phosphor,ctO2 (arterial blood gas analysis)
0,44477f75e8169d2,13,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,126e9dd13932f68,17,negative,0,0,0,0.236515,-0.022340,-0.517413,0.010677,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a46b4402a0e5696,8,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,f7d619a94f97c45,5,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,d9e41465789c2b5,15,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,ae66feb9e4dc3a0,3,positive,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5640,517c2834024f3ea,17,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5641,5c57d6037fe266d,4,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5642,c20c44766f28291,10,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5643,2697fdccbfeb7f7,19,positive,0,0,0,0.694287,0.541564,-0.906829,-0.325903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [357]:
# detecta dados faltantes
column_null = dataset.isnull().sum().sort_values(ascending=False)
column_not_null = dataset.notnull().sum().sort_values(ascending=False)
column_null_percent = (column_null/(column_null + column_not_null))*100
dataset_null_percent = pd.concat({'Nulos': column_null, 'Não nulos': column_not_null, 'Porcentagem': column_null_percent}, axis=1)
dataset_null_percent[dataset_null_percent['Porcentagem']>=90]

                                    Nulos  Não nulos  Porcentagem
Urine - Sugar                        5644          0   100.000000
Mycoplasma pneumoniae                5644          0   100.000000
Partial thromboplastin time (PTT)    5644          0   100.000000
Prothrombin time (PT), Activity      5644          0   100.000000
D-Dimer                              5644          0   100.000000
...                                   ...        ...          ...
Potassium                            5273        371    93.426648
Urea                                 5247        397    92.965982
Creatinine                           5220        424    92.487597
Proteina C reativa mg/dL             5138        506    91.034727
Neutrophils                          5131        513    90.910702

[72 rows x 3 columns]

In [358]:
# cria uma lista das colunas nulas ou quase nulas a serem deletadas
columns_null = dataset_null_percent[dataset_null_percent['Porcentagem']>=90].index.to_list()
columns_null

['Urine - Sugar',
 'Mycoplasma pneumoniae',
 'Partial thromboplastin time\xa0(PTT)\xa0',
 'Prothrombin time (PT), Activity',
 'D-Dimer',
 'Fio2 (venous blood gas analysis)',
 'Urine - Nitrite',
 'Vitamin B12',
 'Lipase dosage',
 'Albumin',
 'Phosphor',
 'Arteiral Fio2',
 'Ferritin',
 'Arterial Lactic Acid',
 'ctO2 (arterial blood gas analysis)',
 'Hb saturation (arterial blood gases)',
 'Total CO2 (arterial blood gas analysis)',
 'pCO2 (arterial blood gas analysis)',
 'Base excess (arterial blood gas analysis)',
 'pO2 (arterial blood gas analysis)',
 'HCO3 (arterial blood gas analysis)',
 'pH (arterial blood gas analysis)',
 'Magnesium',
 'Ionized calcium\xa0',
 'Urine - Ketone Bodies',
 'Urine - Protein',
 'Urine - Esterase',
 'Urine - Hyaline cylinders',
 'Urine - Granular cylinders',
 'Urine - Urobilinogen',
 'Urine - Hemoglobin',
 'Urine - Bile pigments',
 'Urine - Density',
 'Urine - Aspect',
 'Urine - pH',
 'Urine - Crystals',
 'Urine - Red blood cells',
 'Urine - Yeasts',
 'Urine - Leukocytes',
 'Urine - Color',
 'Relationship (Patient/Normal)',
 'Rods #',
 'Myelocytes',
 'Promyelocytes',
 'Metamyelocytes',
 'Myeloblasts',
 'Segmented',
 'Lactic Dehydrogenase',
 'Creatine phosphokinase\xa0(CPK)\xa0',
 'International normalized ratio (INR)',
 'pCO2 (venous blood gas analysis)',
 'pH (venous blood gas analysis)',
 'Total CO2 (venous blood gas analysis)',
 'pO2 (venous blood gas analysis)',
 'Base excess (venous blood gas analysis)',
 'Hb saturation (venous blood gas analysis)',
 'HCO3 (venous blood gas analysis)',
 'Alkaline phosphatase',
 'Gamma-glutamyltransferase\xa0',
 'Indirect Bilirubin',
 'Direct Bilirubin',
 'Total Bilirubin',
 'Serum Glucose',
 'Alanine transaminase',
 'Aspartate transaminase',
 'Strepto A',
 'Sodium',
 'Potassium',
 'Urea',
 'Creatinine',
 'Proteina C reativa mg/dL',
 'Neutrophils']

In [359]:
# dropa as colunas
dataset.drop(columns=columns_null, inplace=True)
dataset

,Patient ID,Patient age quantile,SARS-Cov-2 exam result,"Patient addmited to regular ward (1=yes, 0=no)","Patient addmited to semi-intensive unit (1=yes, 0=no)","Patient addmited to intensive care unit (1=yes, 0=no)",Hematocrit,Hemoglobin,Platelets,Mean platelet volume,...,Adenovirus,Parainfluenza 4,Coronavirus229E,CoronavirusOC43,Inf A H1N1 2009,Bordetella pertussis,Metapneumovirus,Parainfluenza 2,"Influenza B, rapid test","Influenza A, rapid test"
0,44477f75e8169d2,13,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,126e9dd13932f68,17,negative,0,0,0,0.236515,-0.022340,-0.517413,0.010677,...,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,negative,negative
2,a46b4402a0e5696,8,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,f7d619a94f97c45,5,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,d9e41465789c2b5,15,negative,0,0,0,NaN,NaN,NaN,NaN,...,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,ae66feb9e4dc3a0,3,positive,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5640,517c2834024f3ea,17,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5641,5c57d6037fe266d,4,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5642,c20c44766f28291,10,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5643,2697fdccbfeb7f7,19,positive,0,0,0,0.694287,0.541564,-0.906829,-0.325903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [360]:
# Substitui os valores em string para number para facilitar a substituição de nulos restantes pela média
dataset.replace('not_detected', 0, inplace=True)
dataset.replace('detected', 1, inplace=True)
dataset.replace('negative', 0, inplace=True)
dataset.replace('positive', 1, inplace=True)
dataset.replace('absent', 0, inplace=True)
dataset.replace('present', 1, inplace=True)

# Faz a substituição dos valores nulos pela média da coluna
for i in dataset.columns[dataset.isnull().any(axis=0)]:   
    dataset[i].fillna(dataset[i].mean(),inplace=True)
    
dataset

,Patient ID,Patient age quantile,SARS-Cov-2 exam result,"Patient addmited to regular ward (1=yes, 0=no)","Patient addmited to semi-intensive unit (1=yes, 0=no)","Patient addmited to intensive care unit (1=yes, 0=no)",Hematocrit,Hemoglobin,Platelets,Mean platelet volume,...,Adenovirus,Parainfluenza 4,Coronavirus229E,CoronavirusOC43,Inf A H1N1 2009,Bordetella pertussis,Metapneumovirus,Parainfluenza 2,"Influenza B, rapid test","Influenza A, rapid test"
0,44477f75e8169d2,13,0,0,0,0,-2.186214e-09,-1.601319e-08,-3.535004e-10,7.438142e-09,...,0.009615,0.014053,0.006657,0.005917,0.072485,0.001479,0.010355,0.0,0.059756,0.063415
1,126e9dd13932f68,17,0,0,0,0,2.365154e-01,-2.234027e-02,-5.174130e-01,1.067657e-02,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2,a46b4402a0e5696,8,0,0,0,0,-2.186214e-09,-1.601319e-08,-3.535004e-10,7.438142e-09,...,0.009615,0.014053,0.006657,0.005917,0.072485,0.001479,0.010355,0.0,0.059756,0.063415
3,f7d619a94f97c45,5,0,0,0,0,-2.186214e-09,-1.601319e-08,-3.535004e-10,7.438142e-09,...,0.009615,0.014053,0.006657,0.005917,0.072485,0.001479,0.010355,0.0,0.059756,0.063415
4,d9e41465789c2b5,15,0,0,0,0,-2.186214e-09,-1.601319e-08,-3.535004e-10,7.438142e-09,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.059756,0.063415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,ae66feb9e4dc3a0,3,1,0,0,0,-2.186214e-09,-1.601319e-08,-3.535004e-10,7.438142e-09,...,0.009615,0.014053,0.006657,0.005917,0.072485,0.001479,0.010355,0.0,0.059756,0.063415
5640,517c2834024f3ea,17,0,0,0,0,-2.186214e-09,-1.601319e-08,-3.535004e-10,7.438142e-09,...,0.009615,0.014053,0.006657,0.005917,0.072485,0.001479,0.010355,0.0,0.059756,0.063415
5641,5c57d6037fe266d,4,0,0,0,0,-2.186214e-09,-1.601319e-08,-3.535004e-10,7.438142e-09,...,0.009615,0.014053,0.006657,0.005917,0.072485,0.001479,0.010355,0.0,0.059756,0.063415
5642,c20c44766f28291,10,0,0,0,0,-2.186214e-09,-1.601319e-08,-3.535004e-10,7.438142e-09,...,0.009615,0.014053,0.006657,0.005917,0.072485,0.001479,0.010355,0.0,0.059756,0.063415
5643,2697fdccbfeb7f7,19,1,0,0,0,6.942869e-01,5.415639e-01,-9.068291e-01,-3.259033e-01,...,0.009615,0.014053,0.006657,0.005917,0.072485,0.001479,0.010355,0.0,0.059756,0.063415

In [361]:
# iterar pelas colunas do DataFrame
for col in dataset.columns:
    # pula a coluna de ID e as colunas de booleanos para calcular os outliers
    if col in ["Patient ID", 
              "SARS-Cov-2 exam result", 
              "Patient addmited to semi-intensive unit (1=yes, 0=no)", 
              "Patient addmited to intensive care unit (1=yes, 0=no)", 
              "Patient addmited to regular ward (1=yes, 0=no)",
              "Mean platelet volume "]:
        continue
    # calcular o limite superior e inferior para detecção de outliers
    Q1 = dataset[col].quantile(0.25)
    Q3 = dataset[col].quantile(0.75)
    IQR = Q3 - Q1
    lim_sup = Q3 + 1.5 * IQR
    lim_inf = Q1 - 1.5 * IQR

    # identificar os outliers
    outliers = dataset[(dataset[col] < lim_inf) | (dataset[col] > lim_sup)]

    # imprimir o número de outliers e seus valores máximo e mínimo
    print(f"Coluna: {col}")
    print(f"Número de outliers: {len(outliers)}")
    print(f"Máximo outlier: {outliers[col].max()}")
    print(f"Mínimo outlier: {outliers[col].min()}")
    print("\n")

dataset.to_excel('dataset_novo.xlsx', index= False)

Coluna: Patient age quantile
Número de outliers: 0
Máximo outlier: nan
Mínimo outlier: nan


Coluna: Hematocrit
Número de outliers: 603
Máximo outlier: 2.6627037525177
Mínimo outlier: -4.501419544219971


Coluna: Hemoglobin
Número de outliers: 603
Máximo outlier: 2.671867847442627
Mínimo outlier: -4.345602989196777


Coluna: Platelets
Número de outliers: 602
Máximo outlier: 9.532033920288086
Mínimo outlier: -2.552426099777222


Coluna: Red blood Cells
Número de outliers: 602
Máximo outlier: 3.645706176757812
Mínimo outlier: -3.970608234405518


Coluna: Lymphocytes
Número de outliers: 602
Máximo outlier: 3.764099597930908
Mínimo outlier: -1.865069627761841


Coluna: Mean corpuscular hemoglobin concentration (MCHC)
Número de outliers: 602
Máximo outlier: 3.3310706615448
Mínimo outlier: -5.431808471679688


Coluna: Leukocytes
Número de outliers: 602
Máximo outlier: 4.522041797637939
Mínimo outlier: -2.020302534103394


Coluna: Basophils
Número de outliers: 602
Máximo outlier: 11.07821941375732
Mínimo outlier: -1.140143752098083


Coluna: Mean corpuscular hemoglobin (MCH)
Número de outliers: 602
Máximo outlier: 4.098546028137207
Mínimo outlier: -5.937603950500488


Coluna: Eosinophils
Número de outliers: 602
Máximo outlier: 8.350875854492188
Mínimo outlier: -0.8355076909065247


Coluna: Mean corpuscular volume (MCV)
Número de outliers: 602
Máximo outlier: 3.410979986190796
Mínimo outlier: -5.10158109664917


Coluna: Monocytes
Número de outliers: 601
Máximo outlier: 4.533397197723389
Mínimo outlier: -2.163721323013306


Coluna: Red blood cell distribution width (RDW)
Número de outliers: 602
Máximo outlier: 6.982183933258057
Mínimo outlier: -1.598094344139099


Coluna: Respiratory Syncytial Virus
Número de outliers: 1354
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Influenza A
Número de outliers: 1354
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Influenza B
Número de outliers: 1354
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Parainfluenza 1
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: CoronavirusNL63
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Rhinovirus/Enterovirus
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Coronavirus HKU1
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Parainfluenza 3
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Chlamydophila pneumoniae
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Adenovirus
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Parainfluenza 4
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Coronavirus229E
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: CoronavirusOC43
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Inf A H1N1 2009
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Bordetella pertussis
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Metapneumovirus
Número de outliers: 1352
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Parainfluenza 2
Número de outliers: 0
Máximo outlier: nan
Mínimo outlier: nan


Coluna: Influenza B, rapid test
Número de outliers: 820
Máximo outlier: 1.0
Mínimo outlier: 0.0


Coluna: Influenza A, rapid test
Número de outliers: 820
Máximo outlier: 1.0
Mínimo outlier: 0.0